### ISSUE TITLE
expansion of '<bod' gives incorrect result

### ISSUE THREAD

**Issue by Alexey-T** [rickard67/Emmet-Pascal#11]
HTML syntax.

- Expansion of `<bod` gives strange line `<bod</bo>`.
- Expansion of `<body` gives bad line `<body</bod>`

**Comment by Alexey-T** [comment]
Also - the caret mark is missed in both cases. so my program puts caret before the result line.

**Comment by rickard67** [comment]
Neither of those strings should be expanded. <bod and <body are not Emmet abbreviations. "body" is. I'll look into it.

**Comment by Alexey-T** [comment]
I agree, not Emmet abbrevs. Then the Emmet must not work in this case, and not give any strange result.
