### ISSUE TITLE
wrap with abbreviation

### ISSUE THREAD

**Issue by ildarkhasanshin** [rickard67/Emmet-Pascal#12]
```test```

1
wrap with abbreviation -> p
```
<p>
    test
</p>
```

2
wrap with abbreviation -> p*
```<p>test</p>```

---

`sublime text 4`
wrap with abbreviation -> p == wrap with abbreviation -> p*
```<p>test</p>```

---

https://github.com/CudaText-addons/cuda_emmet/issues/2#issuecomment-1849495052

**Comment by rickard67** [comment]
Should work now. Thanks!

**Comment by Alexey-T** [comment]
```

function TEmmet.GetLineCount(const s: string): Integer;
var
  n: Integer;
begin
  Result := 1;
  n := Pos(#13,s);
  while n > 0 do
  begin
    Inc(Result);
    n := PosEx(#13,s,n+1);
  end;
end;
```
In my app, text buffer EOLs are chr(10), so how will it work?
do you handle text made by Emmet? if so, all ok.

**Comment by rickard67** [comment]
Changed Pos(#13,s) => Pos(#10,s). Should work fine since no one uses only CR as linefeed anymore.
