### ISSUE TITLE
7 equal fragments in code

### ISSUE THREAD

**Issue by Alexey-T** [rickard67/Emmet-Pascal#13]
```
  Result := StringReplace(Result, '\n', #13#10, [rfReplaceAll]);
  Result := StringReplace(Result, '\t', #9, [rfReplaceAll]);
```
occurs N times. DRY principle.

**Comment by rickard67** [comment]
True... but it's not actually executed N times when processing an expression.

Would it be consistent with the DRY principal to simply add the two lines inside a function and call the function instead?

**Comment by Alexey-T** [comment]
yes. solved in git.
