### ISSUE TITLE
Lorem - need to make it like in VS Code

### ISSUE THREAD

**Issue by Alexey-T** [rickard67/Emmet-Pascal#2]
VSCode allows this

1)
lorem[tab] 
->
lorem text with about 30 words

Currently Emmet-Pascal makes `<lorem></lorem>` - nonsense.

2) 
p*2>lorem[tab]
->
```
<p>
  Lorem ipsum dolor sit amet, consectetur adipisicing elit. Qui dicta minus
  molestiae vel beatae natus eveniet ratione temporibus aperiam harum alias
  officiis assumenda officia quibusdam deleniti eos cupiditate dolore doloribus!
</p>
<p>
  Ad dolore dignissimos asperiores dicta facere optio quod commodi nam tempore
  recusandae. Rerum sed nulla eum vero expedita ex delectus voluptates rem at
  neque quos facere sequi unde optio aliquam!
</p>
```

Please make like VS Code.

**Comment by rickard67** [comment]
Fixed. Thanks!

**Comment by Alexey-T** [comment]
Thanks but I see bug with code.

- `lorema` and `loremm` must NOT expand at all - must check word-boundary after 'lorem'
- after I expanded lorem, I make a new file (empty!) and expand `p*4` --> this gives lorem too!
as it's in the memory.

![Screenshot from 2022-03-14 17-35-07](https://user-images.githubusercontent.com/4154978/158194440-0363e1bd-f415-4ebf-9932-2bf69ab7df7f.png)

**Comment by Alexey-T** [comment]
@rickard67

**Comment by rickard67** [comment]
Should work better now in latest version.

**Comment by Alexey-T** [comment]
Great; thanks for the support!
