### ISSUE TITLE
unneeded space char before the 'class='

### ISSUE THREAD

**Issue by Alexey-T** [rickard67/Emmet-Pascal#4]
img, and some other tags (2-4 tags, or all other tags?) give redundant space before `class="nn"`

`img.nn` ->
```
<img src="" alt=""  class="nn"/>
```

`base.nn` ->
```
<base href=""  class="nn"/>
```

**Comment by Alexey-T** [comment]
@rickard67

**Comment by NaincyKumariKnoldus** [comment]
Hey @Alexey-T Can I do this please?

**Comment by Alexey-T** [comment]
What do you mean.

**Comment by NaincyKumariKnoldus** [comment]
Hey @Alexey-T I mean can I remove this space and raise a PR for this.

**Comment by Alexey-T** [comment]
Please do it :)

**Comment by Alexey-T** [comment]
I am not sure @rickard67 reads here. We need to ping him at the RJ-TextEd forum

**Comment by NaincyKumariKnoldus** [comment]
Hey @rickard67

**Comment by rickard67** [comment]
Thanks. I'll look into it when I get the time. 

I would appreciate it if you want to create a pull request. I'll check it when I can and merge it with the repository.

**Comment by NaincyKumariKnoldus** [comment]
Hey @rickard67 I found class in demo.dproj file. I have to correct it there?

**Comment by rickard67** [comment]
The problem can be found in the .\emmet\emmet.pas file. It seems the code adds an extra space between "alt" and "class" instead of "class="nn"" and "/>".

**Comment by rickard67** [comment]
It's been fixed in the upcoming update.
