### ISSUE TITLE
tag 'track' / 'wbr' must be void, but it is not

### ISSUE THREAD

**Issue by Alexey-T** [rickard67/Emmet-Pascal#5]
https://html.spec.whatwg.org/multipage/syntax.html#void-elements tells that `track` is a void tag!
but `track.nn` ->
```
<track class="n"></track>
```

`wbr` must also be void!
but `wbr.nn` ->
```
<wbr class="nn"></wbr>
```

**Comment by Alexey-T** [comment]
@rickard67

**Comment by rickard67** [comment]
Thanks, I'll fix it as soon as I can. I'm a bit busy at the moment, but I'll get to it eventually.

**Comment by rickard67** [comment]
This can easily be fixed by adding new lines to the Snippets.ini file.

E.g.
```
track=<track />
wbr=<wbr />
```

Added in the upcoming update.
