### ISSUE TITLE
in my text editor, many non-abbreviations are expanded to paired 'tags'

### ISSUE THREAD

**Issue by Alexey-T** [rickard67/Emmet-Pascal#8]
can we avoid the expansion of 
```
ok?
ok:
ok,
```
etc? ie the engine should not expand them.

![dd](https://user-images.githubusercontent.com/4154978/185811464-a9af293d-79bb-4776-bf13-87bc474e441d.gif)

**Comment by Alexey-T** [comment]
i solved this on app level, but if you can improve Emmet here, will be ok too.

**Comment by Alexey-T** [comment]
'!' is valid abbrev char, so my fix was not touching this char, so yet - 'ok!' expands! please don't expand 'ok!'.

**Comment by rickard67** [comment]
Added a new HTML tag list that can be used for validation.

From emmet.pas
-----------------------------------------------
Validate HTML tags
    You can add a list of all valid HTML tags. Use this to avoid expanding illegal HTML tags.

    E.g. p{tab} should be expanded to <p></p>, but n{tab} should not be expanded to <n></n>.

    Use this function to add your list:

        AddHTMLTagListForValidation(const AList: TStringList);
